package myBatis.dao;

import java.util.List;

import myBatis.model.Machine;
import org.mybatis.cdi.Mapper;

@Mapper
public interface MachineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MACHINE
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MACHINE
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    int insert(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MACHINE
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    Machine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MACHINE
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    List<Machine> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MACHINE
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    int updateByPrimaryKey(Machine record);
}