package myBatis.dao;

import java.util.List;

import entities.Weight;
import myBatis.model.Zone;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ZoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ZONE
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ZONE
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    int insert(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ZONE
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    Zone selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ZONE
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    List<Zone> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ZONE
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    int updateByPrimaryKey(Zone record);

    List<Weight> selectWeightsForZone();
}