package myBatis.model;

public class Machine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MACHINE.ID
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MACHINE.NAME
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MACHINE.ID
     *
     * @return the value of PUBLIC.MACHINE.ID
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MACHINE.ID
     *
     * @param id the value for PUBLIC.MACHINE.ID
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MACHINE.NAME
     *
     * @return the value of PUBLIC.MACHINE.NAME
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MACHINE.NAME
     *
     * @param name the value for PUBLIC.MACHINE.NAME
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}