package myBatis.model;

import lombok.Getter;
import lombok.Setter;


public class Weight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WEIGHT.ID
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WEIGHT.NAME
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WEIGHT.ZONE_ID
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    private Integer zoneId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WEIGHT.ID
     *
     * @return the value of PUBLIC.WEIGHT.ID
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WEIGHT.ID
     *
     * @param id the value for PUBLIC.WEIGHT.ID
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WEIGHT.NAME
     *
     * @return the value of PUBLIC.WEIGHT.NAME
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WEIGHT.NAME
     *
     * @param name the value for PUBLIC.WEIGHT.NAME
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WEIGHT.ZONE_ID
     *
     * @return the value of PUBLIC.WEIGHT.ZONE_ID
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WEIGHT.ZONE_ID
     *
     * @param zoneId the value for PUBLIC.WEIGHT.ZONE_ID
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }

    @Getter @Setter
    private Zone zone;

}