package myBatis.model;

import entities.Weight;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

public class Zone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ZONE.ID
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ZONE.NAME
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ZONE.ID
     *
     * @return the value of PUBLIC.ZONE.ID
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ZONE.ID
     *
     * @param id the value for PUBLIC.ZONE.ID
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ZONE.NAME
     *
     * @return the value of PUBLIC.ZONE.NAME
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ZONE.NAME
     *
     * @param name the value for PUBLIC.ZONE.NAME
     *
     * @mbg.generated Tue Apr 06 21:15:39 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    @Getter @Setter
    private List<Weight> weights = new ArrayList<>();
}